services:
  caddy:
    image: caddybuilds/caddy-cloudflare:2.11.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./secrets.env # CLOUDFLARE_API_TOKEN
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/usr/local/share/ca-certificates:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    command: sh -c "update-ca-certificates && caddy run --config /etc/caddy/Caddyfile"
    networks:
      - bridge_net

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/udp
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /hdds/media:/media
      - /hdds/media2:/media2:ro
    restart: unless-stopped
    env_file:
      - ./jellyfin/vars.env # JELLYFIN_PublishedServerUrl
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - bridge_net

  db:
    image: mariadb:11.8
    container_name: db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --performance-schema=OFF
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./secrets.env # MYSQL_ROOT_PASSWORD, MYSQL_PASSWORD
      - ./nextcloud/vars.env # MYSQL_DATABASE, MYSQL_USER
    networks:
      - bridge_net

  nextcloud:
    image: nextcloud:33.0.2
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
      - ./nextcloud/config/config.php:/var/www/html/config/config.php
      - /hdds/media2:/var/www/html/data/media
    env_file:
      - ./secrets.env # MYSQL_PASSWORD
      - ./nextcloud/vars.env # MYSQL_DATABASE, MYSQL_USER, MYSQL_HOST
    depends_on:
      - db
    networks:
      - bridge_net

  filebrowser:
    image: gtstef/filebrowser:1.3.0-stable-slim
    container_name: filebrowser
    restart: unless-stopped
    ports: 
      - 8081:80
    env_file:
      - ./secrets.env # FILEBROWSER_ADMIN_PASSWORD, FILEBROWSER_OIDC_CLIENT_SECRET
    volumes:
      - ./filebrowser/data:/home/filebrowser/data
      - /hdds/media:/folder
    networks:
      - bridge_net

volumes:
  caddy_data:
  caddy_config:
  db_data:
  nextcloud_data:

networks:
  bridge_net:
    driver: bridge